---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2019/4/9 16:25
---

if (redis.call('exists', KEYS[1]) == 0) then   --  exists 判断key是否存在
redis.call('hset', KEYS[1], ARGV[2], 1)    --如果不存在，hset存哈希表
redis.call('pexpire' ,KEYS[1] ,ARGV[1]);  --设置过期时间
return nil                            -- 返回null 就是加锁成功
end;
if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then   -- 如果key存在，查看哈希表中是否存在
redis.call('hincrby' ,KEYS[1], ARGV[2] ,1);   -- 给哈希中的key加1，代表重入1次，以此类推
redis.call('pexpire', KEYS[1], ARGV[1]);  -- 重设过期时间
return nil;
end;
return redis.call('pttl', KEYS[1]); --如果前面的if都没进去，说明ARGV2 的值不同，也就是不是同                  一线程的锁，这时候直接返回该锁的过期时间
