---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2019/4/9 16:24
---

local times = redis.call('incr',KEYS[1])

if times == 1 then
    redis.call('expire',KEYS[1], ARGV[1])
end

if times > tonumber(ARGV[2]) then
    return 0
end
return 1