env:
  type: @env.type@

server:
  port: 8084

spring:
  thymeleaf:
    enabled: true #开启MVC Thymeleaf视图解析（默认值：true）
    cache: true #开启模板缓存（默认值：true）
    check-template: true
    check-template-location: true #检查模板位置是否正确（默认值:true）
    servlet:
      content-type: text/html
    encoding: UTF-8 #模板编码

  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/mydata?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    connectTimeout: 350000
    connection-timeout: 350000
    type: com.zaxxer.hikari.HikariDataSource
    # 配置了还是3秒超时
    hikari:
      connection-timeout: 300000

#验证连接的有效性
spring.datasource.test-while-idle: true
#获取连接时候验证，会影响性能
spring.datasource.test-on-borrow: true


logging:
  path: @stone.loggingPath@
  level:
    root: @stone.loggingLevel@

valuetest:
  test1: @valuetest.test1@


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lsh.demo.bootstone.dao.mysql


#dubbo:
#  application:
#    name: bootstone
#  protocol:
#    name: dubbo
#    port: @dubbo.port@
#  registry:
#    address: @dubbo.address@
#    check: false
#  consumer:
#    check: false


#  port: 8082

---
spring:
  profiles: dev

server:
  port: 8082

---
spring:
  profiles: prod

server:
  port: 8083