env:
  type: @env.type@

server:
  port: 8082

spring:
  thymeleaf:
    enabled: true #开启MVC Thymeleaf视图解析（默认值：true）
    cache: true #开启模板缓存（默认值：true）
    check-template: true
    check-template-location: true #检查模板位置是否正确（默认值:true）
    servlet:
      content-type: text/html
    encoding: UTF-8 #模板编码

logging:
  path: @stone.loggingPath@
  level:
    root: @stone.loggingLevel@